### ISSUE TITLE
fa-data: wrong attribute values for appellation types, and some missing types

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#15]
## Wrong appellation type
```
<https://sk.acdh.oeaw.ac.at/p_37622/appellation/1> a ns1:E33_E41_Linguistic_Appellation ;
    rdfs:label "„Schadenfroh“;"@und ;
    ns1:P2_has_type <https://sk.acdh.oeaw.ac.at/types/person/persname/sk> ;
    rdf:value "„Schadenfroh“;" .
```
- [x] Line 4, the object in has_type, is generated from `persName/@type` ("sk"), should be from `@subtype` ("pref" or "pseud").

## Two types for one Appellation
- [x] If persName @subtype="pref" and "pseud" have the same string value, create only one E33_E41_Linguistic_Appellation and assign both types to it (so: one more triple with "ns1:P2_has_type").

## Adding male and female name types
- [x] If a persName is `@subtype="pref" and parent::person[sex/@value="male"]`:
        Add: ns1:P2_has_type <https://sk.acdh.oeaw.ac.at/types/person/persname/male>
- [x] If a persName is `@subtype="pref" and parent::person[sex/@value="female"]`:
        Add: ns1:P2_has_type <https://sk.acdh.oeaw.ac.at/types/person/persname/female>

**Comment by BOberreither** [comment]
@linxOD  (male/female still open, as far as i can see)

**Comment by BOberreither** [comment]
@linxOD Sorry, couldn't see the change (same as in #15) ...

**Comment by BOberreither** [comment]
@linxOD 
### One strange error: 
Superfluous one-line-statements with non-existing subject, e.g.:
```
sk:p_40067 a cidoc:E21_Person ;
        rdfs:label "Confuser Leser"@und ;
        cidoc:P1_is_identified_by <https://sk.acdh.oeaw.ac.at/p_40067/appellation/0>,
            <https://sk.acdh.oeaw.ac.at/p_40067/identifier/idno/0>,
            <https://sk.acdh.oeaw.ac.at/p_40067/identifier/p_40067> .

    <https://sk.acdh.oeaw.ac.at/p_40067/appellation/1> cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/person/persname/male> .
```
Person is fine, appellation/1 should not exist (appellation/0 is fine).
Maybe it has to do with appellations that get 3 types at once (pref, pseud and male/female); all my samples suggest that. If appellation/0 has three types, there also seems to exist such an 'empty' appellation/1.

**Comment by linxOD** [comment]
I found an example in the data (listperson.xml) where there is a `subtype` but with an empty string.
Currently no `P2_has_type` will be created or should there be a default value? e.g. "pref"

```
<person xml:id="p_40022" status="checked">
      <persName type="sk" subtype="pref">Vautel, Clément</persName>
      <persName type="sk" subtype="">Vaulet, Clément-Henri</persName>
      ....
```
