### ISSUE TITLE
Minor: person appellation type male/female

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#18]
## person appellation type male/female

Just like in lk data: If the persName element has an @sex, use it's value for the resp. line in the E33_E41 statement:
```
cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/person/persname/male>,
```
– instead of the `person/sex` element.
Thanks!

**Comment by BOberreither** [comment]
@linxOD  - Seems like this still needs to be done.

**Comment by linxOD** [comment]
same as #15
