### ISSUE TITLE
Fackel-Periodical-F24 

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#22]
This looks like a long one, but it's mostly copy and paste for you.

The information about _Die Fackel_ as a whole - i.e. about the periodical-statement incl. related statements - has to be extended by an Identifier and an Appellation-Part. Because the data is nowhere to be found (we would have to extend the cascaded.xml first), and because the whole thing concerns only one case anyway, please just insert these lines:

- [x] for the "<https://sk.acdh.oeaw.ac.at/01/published-expression>" statement:

`cidoc:P1_is_identified_by <https://sk.acdh.oeaw.ac.at/01/identifier/idno/0>`

- [x] a new identifier-statement
```
<https://sk.acdh.oeaw.ac.at/01/identifier/idno/0> a cidoc:E42_identifier ;
  rdfs:label "Identifier: https://fackel.oeaw.ac.at/F/001,0u1"@en ;
  cidoc:P1i_identifies <https://sk.acdh.oeaw.ac.at/01/published-expression> ;
  cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/idno/URL/fackel> ;
  rdf:value "https://fackel.oeaw.ac.at/F/001,0u1" .
```

- [x] for the appellation statement another object for "cidoc:P106_is_composed_of": <https://sk.acdh.oeaw.ac.at/01/appellation-date/0>

- [x] The corresponding E90-statement:

```
<https://sk.acdh.oeaw.ac.at/01/appellation-date/0> a cidoc:E90_Symbolic_Object ;
  rdfs:label "Appellation Part: 1899-1936"@en ;
  cidoc:P106i_forms_part_of <https://sk.acdh.oeaw.ac.at/01/appellation/0> ;
  cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/appellation/date> ;
  rdf:value "1899-1936" .
```

 That's it!
(ps.: By the way, the other E90 in this case is called lt URI "appellation-num", although it is the title ... maybe change? Occurs 2 times, once as object in appellation-, once as subject in E90-statement).

**Comment by BergListe** [comment]
Everything should be done - even the renaming of appellation-num to appellation-title

New file was pushed to https://gitlab.oeaw.ac.at/acdh-ch/ace/semanticKraus/fackel-export/-/blob/main/rdf/texts.ttl?ref_type=heads

**Comment by BOberreither** [comment]
@BergListe Nice! One tiny thing: Line 451, has "lt;" instead of "<".

**Comment by BergListe** [comment]
Fixed it and uploaded source to: https://github.com/semantic-kraus/fa-data/blob/main/data/xsl/fackel_rdf.xsl
