### ISSUE TITLE
Value and label of Symbolic Object "appellation-num"

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#23]
E90-appellation-parts with "appellation-num"-URIs currently show the whole attribute value in rdf:value and rdfs:label.
```
<https://sk.acdh.oeaw.ac.at/issue001/appellation-num/0> a cidoc:E90_Symbolic_Object ;
rdfs:label "Appellation Part: issue001"@en ;
[...]
rdf:value "issue001" .
```
Pleace replace "issue001" with "1", so that rdf:value is only "1", rdfs:label is "Appellation Part: 1". 
Doesn't change in the URI. Thanks!

**Comment by BergListe** [comment]
Done, see https://gitlab.oeaw.ac.at/acdh-ch/ace/semanticKraus/fackel-export/-/blob/main/rdf/texts.ttl?ref_type=heads

**Comment by BOberreither** [comment]
@BergListe Looks good mostly, but I also get a lot of "NaN"s: e.g. for <https://sk.acdh.oeaw.ac.at/issue806/appellation-num/0> (as opposed, strangely, to <https://sk.acdh.oeaw.ac.at/issue810/appellation-num/0>).

**Comment by BergListe** [comment]
I think, I found the problem!
The attribute value looks like this `issue="180-181"` and hence cannot be converted to a numeric value.

**Comment by BergListe** [comment]
No more NaN values! https://github.com/semantic-kraus/fa-data/blob/main/data/xsl/fackel_rdf.xsl
