### ISSUE TITLE
Fackel Texts - minor: NaN in label

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#33]
Some Issue-F22-Labels look like `Die Fackel Nr. NaN (Issue)`. Seems to be where there is a from-to number.

**Comment by BergListe** [comment]
Done

**Comment by BOberreither** [comment]
@BergListe I see you cut the "-xyz" part of the issue nr, leaving only the first one to three digits; it's an option. I say: In the spirit of prioritization, maybe we revisit this one after the more pressing issues are resolved, ok?

**Comment by BergListe** [comment]
What I did was a typical engineering approach: The mission was to eleminate the NaN value. As we now both know this doesn't solve the original problem... I fixed it now the way you expected it be, I hope.
