### ISSUE TITLE
Identifier-o-Rama

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#35]
## Change an Identifier's E55_Type
Currently:
 "https://sk.acdh.oeaw.ac.at/types/idno/GND"
Change to:
 "https://sk.acdh.oeaw.ac.at/types/idno/gnd"

Currently:
 "https://sk.acdh.oeaw.ac.at/types/idno/PMB"
Change to:
 "https://sk.acdh.oeaw.ac.at/types/idno/pmb"

## Change an Identifier and it's E55_Type
Currently:
 "https://sk.acdh.oeaw.ac.at/types/idno/WikiData" and  "Q75505"
Change to: 
 "https://sk.acdh.oeaw.ac.at/types/idno/URL/wikidata" and "https://www.wikidata.org/wiki/Q75505"

**Comment by linxOD** [comment]
changed all ids to URL/URI
"https://sk.acdh.oeaw.ac.at/types/idno/URL/gnd"
"https://sk.acdh.oeaw.ac.at/types/idno/URL/pmb"
"https://sk.acdh.oeaw.ac.at/types/idno/URL/uri"
"https://sk.acdh.oeaw.ac.at/types/idno/URL/geonames"
"https://sk.acdh.oeaw.ac.at/types/idno/URL/wikidata"

**Comment by BOberreither** [comment]
@linxOD In case the current data already includes your fixes (in Varuna):

- [ ] I found a type called `<https://sk.acdh.oeaw.ac.at/types/idno/GDN>` (typo in URI), and a type called `<https://sk.acdh.oeaw.ac.at/types/idno/GND>` - please turn them both into `<https://sk.acdh.oeaw.ac.at/types/idno/URL/gnd>` and add the URL-part to the rdf:value and rdfs:label.

- [ ] Also these spellings of idno wikidata:
- <https://sk.acdh.oeaw.ac.at/types/idno/WikData>
- <https://sk.acdh.oeaw.ac.at/types/idno/WikiData>
- <https://sk.acdh.oeaw.ac.at/types/idno/WIkiData>
- <https://sk.acdh.oeaw.ac.at/types/idno/WkiData>
Please turn them all into URLs (label and value), and change type to
- <https://sk.acdh.oeaw.ac.at/types/idno/URL/wikidata>

- [ ] Also there is a type <https://sk.acdh.oeaw.ac.at/types/idno/PMB> that should be <https://sk.acdh.oeaw.ac.at/types/idno/URL/pmb>

- [ ] Also the type <https://sk.acdh.oeaw.ac.at/types/idno/URI>, while actually correct, could be turned into <https://sk.acdh.oeaw.ac.at/types/idno/URL/fackel> - that's the type in lk named graph.

- [ ] Also please change <https://sk.acdh.oeaw.ac.at/types/idno/sonstiges> to <https://sk.acdh.oeaw.ac.at/types/idno/URL/sonstiges>, it's more specific.

- [ ] It seems that there are different identifiers all typed (unspecifically) as <https://sk.acdh.oeaw.ac.at/types/idno> - any way to specify there type? Where is this broad type applied?
