### ISSUE TITLE
Fackel Texts - Minor: Get Rid of Some E90 Values (So Sad.)

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#38]
Some Appellation Parts (E90 Symbolic Object) have two rdf:values. Sadly, for display reasons (see [here](https://sk.acdh-dev.oeaw.ac.at/resource/?uri=https%3A%2F%2Fsk.acdh.oeaw.ac.at%2Fissue474%2Fpublished-expression)) we have to get rid of one of them.
- The date appellation part can have "Mai 1918" and "1918-05" as values. Get rid of the second one.
- The volume appellation part can have "20" and "XX. Jahr" as values. Get rid of the second one, add "Vol. " in front of the first one.

One learns never out.

Thanks!

**Comment by BergListe** [comment]
Done
