### ISSUE TITLE
Recreate fackeltexts cascaded from google sheet

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#39]
... because I eliminated some errors there. Thanks!

**Comment by BergListe** [comment]
- [x]  Convert Google Sheet to Excel and remove "for deletion" rows
- [x]  Convert Excel rows to FackelTexts.xml
- [x] Upload FackelTexts.xml to eXist
- [x] Call fillEndParId.xql and copy its result into fackelTexts_with_endParIds.xml
- [x] Transform fackelTexts_with_endParIds.xml with cascade.xsl to fackelTexts_cascaded.xml
- [x] Git push to Github & Gitlab
