### ISSUE TITLE
Identifier Problem

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#40]
Many globIDs for text passages start with "n2_"; however the underline is eliminated in the process of creating a permalink, so "n2_XXXX" and "n_2XXXX" turn into the same permalink identifier "n2XXXX".

An example: https://fackel.oeaw.ac.at/?globId=fackeln29790 is derived from n2_9790, which is the last mention on the last page of the last issue, but since it could also be derived from n_29790, it points to a mention in issue 155.

Could you change the permalinks (in our data and in the Fackel online) to keep the "_"?

There are also some identifiers that look like this: "https://sk.acdh.oeaw.ac.at/name_200001/identifier/idno/0>"
Is "name_200001" another globID value? If so, please take it into account for permalinks / identifiers as well.

**Comment by BergListe** [comment]
there is already a solution built into fackel online that comes without adding underscores

**Comment by BOberreither** [comment]
@BergListe Ah, ok; so what does the permalink to, e.g., n2_9790 look like?

**Comment by BergListe** [comment]
- `n_XXXX` becomes `fackelnXXXX` 
- `n2_XXXX` becomes `fackelxXXXX`
- `name_XXXX` becomes `fackelyXXXX`

I know this isn't a very beautiful solution, but I had to find a quick fix because i ran into the same problem as you observed.

**Comment by BOberreither** [comment]
@BergListe Ok, looks fine to me; but in our data we have about 108.000 identifiers that have URLs of the first kind as their values, but zero URLs like 2 and 3. I looked it up – they are not being built, because they don't fit the pattern "n_", I guess. 
Look here: This one has type Fackel URL, but its value is just the naked ID:
https://sk.acdh-dev.oeaw.ac.at/resource/?uri=https%3A%2F%2Fsk.acdh.oeaw.ac.at%2Fn2_1033%2Fidentifier%2Fidno%2F1
Anyway, this problem has less priority than the ghost mention one. Just thought, maybe they were related.

**Comment by BergListe** [comment]
Oh I see. Where do the URIs come from? Who created them?

**Comment by BOberreither** [comment]
I thought they were built in the process of creating the fackel mentions? Since they are Identifiers of text passages in Die Fackel?

**Comment by BergListe** [comment]
Ok, I'll have a look at it when I'm back on the computer after Christmas, ie. December, 27th.

**Comment by BOberreither** [comment]
Thanks!

**Comment by BergListe** [comment]
Corrected.
