### ISSUE TITLE
Still including mentions from adverts and cover pages

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#41]
There are 8680 mentions that are all attributed to the same text passage "https://sk.acdh.oeaw.ac.at//passage/1" (which is attributed to the wrong URI "https://sk.acdh.oeaw.ac.at/" – which is currently DWs "Polenlieder" - funny, somewhat). They stem from adverts and cover pages, aka non-texts.
I'll look for a mistake in the google sheet, otherwise I don't know an answer ... Maybe in the mechanism filtering out these mentions?

It seems like it's not limited to a portion of Die Fackel, it starts with the first mention on cover one of issue one and ends with a mention on the last page of the last issue.

**Comment by BergListe** [comment]
looks like we have to go and review this whole thing...

**Comment by BergListe** [comment]
The problem is that I have always looked in the wrong file. The cause lies in Mentions.xml, because this no longer takes into account the restrictions that were made in fackelTexts.xml. This means that all mentions are processed, including those from the unwanted sections of the Fackel.

**Comment by BergListe** [comment]
Done.
