### ISSUE TITLE
Minor minor: has-type-typo

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#42]
See, e.g., https://sk.acdh-dev.oeaw.ac.at/resource/?uri=https%3A%2F%2Fsk.acdh.oeaw.ac.at%2Ftext10013%2Ftitle%2F0

This title is linked to its E55 Type via "P2_has_Type" - but it's "P2_has_type" - please fix, thanks!

**Comment by BergListe** [comment]
There were two places this typo could be found - I fixed both of them.
